/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DangNhapDAO;
import DAO.DocGiaDAO;
import DAO.PhieuMuonDAO;
import DAO.TaiLieuDAO;
import DAO.ChiTietPhieuMuonDAO;
import POJO.ChiTietPhieuMuon;
import POJO.PhieuMuon;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Administrator
 */
public class formPhieuMuon extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Calendar hanTra = Calendar.getInstance();
    boolean check = false;
    String maNV;
    int temp2;
    /**
     * Creates new form QL_MuonTaiLieu
     */
    public formPhieuMuon() {
        initComponents();
        maNV = DangNhapDAO.LoadMaNhanVienHienTai();
        dtm.addColumn("Mã Phiếu mượn");
        dtm.addColumn("Mã Nhân viên");
        dtm.addColumn("Mã Đọc giả");
        dtm.addColumn("Trạng thái");
        dtm.addColumn("Ngày lập phiếu");
        setEnable_False();
        hienThiDanhSach();
        tblDSPhieuMuon.setModel(dtm);
    }
    private void hienThiDanhSach() {
        ArrayList<PhieuMuon> ds = PhieuMuonDAO.DanhSachPhieuMuon();
        dtm.setRowCount(0);
        for(PhieuMuon pm: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(pm.getMaPhieuMuon());
            v.add(pm.getMaNVLap());
            v.add(pm.getMaDG());
            v.add(pm.getTinhTrang());
            v.add(pm.getNgayLap());
            dtm.addRow(v);
        }
        tblDSPhieuMuon.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaPhieuMuon = new javax.swing.JTextField();
        txtMaDocGia = new javax.swing.JTextField();
        txtTenDG = new javax.swing.JTextField();
        txtNgayMuon = new javax.swing.JTextField();
        txtMaTL = new javax.swing.JTextField();
        txtTenTL = new javax.swing.JTextField();
        txtSLMuon = new javax.swing.JTextField();
        txtHanTra = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnTKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSPhieuMuon = new javax.swing.JTable();
        nen = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(865, 555));
        setMinimumSize(new java.awt.Dimension(865, 555));
        setPreferredSize(new java.awt.Dimension(865, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(154, 221, 253));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết Phiếu Mượn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Mã phiếu mượn:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Mã đọc giả:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Tên đọc giả:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Ngày mượn:");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Hạn trả:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Số lượng mượn:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mã tài liệu:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tên tài liệu:");

        txtMaPhieuMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaPhieuMuon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhieuMuonActionPerformed(evt);
            }
        });

        txtMaDocGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaDocGia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaDocGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaDocGiaFocusLost(evt);
            }
        });
        txtMaDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDocGiaActionPerformed(evt);
            }
        });

        txtTenDG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenDG.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDGActionPerformed(evt);
            }
        });

        txtNgayMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNgayMuon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNgayMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayMuonActionPerformed(evt);
            }
        });

        txtMaTL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaTL.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaTL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaTLFocusLost(evt);
            }
        });
        txtMaTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTLActionPerformed(evt);
            }
        });

        txtTenTL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenTL.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTLActionPerformed(evt);
            }
        });

        txtSLMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSLMuon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSLMuon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSLMuonFocusLost(evt);
            }
        });
        txtSLMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLMuonActionPerformed(evt);
            }
        });

        txtHanTra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHanTra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtHanTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHanTraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(46, 46, 46)
                        .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTenTL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSLMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(txtMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSLMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtHanTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 790, 190));

        btnThem.setBackground(new java.awt.Color(154, 221, 253));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 90, -1));

        btnXoa.setBackground(new java.awt.Color(154, 221, 253));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 90, -1));

        btnSua.setBackground(new java.awt.Color(154, 221, 253));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 90, -1));

        btnMoi.setBackground(new java.awt.Color(154, 221, 253));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 90, -1));

        btnTKiem.setBackground(new java.awt.Color(154, 221, 253));
        btnTKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTKiem.setText("Tìm kiếm");
        btnTKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 170, -1));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 460, -1));

        tblDSPhieuMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblDSPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title1", "Title2", "Title3", "Title4"
            }
        ));
        tblDSPhieuMuon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDSPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSPhieuMuonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSPhieuMuon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 790, 180));

        nen.setBackground(java.awt.Color.pink);
        nen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen3.png"))); // NOI18N
        nen.setMaximumSize(new java.awt.Dimension(735, 555));
        nen.setMinimumSize(new java.awt.Dimension(735, 555));
        getContentPane().add(nen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 870, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhieuMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhieuMuonActionPerformed

    private void txtMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDocGiaActionPerformed

    }//GEN-LAST:event_txtMaDocGiaActionPerformed

    private void txtTenDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDGActionPerformed

    private void txtNgayMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayMuonActionPerformed

    private void txtMaTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTLActionPerformed

    private void txtTenTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTLActionPerformed

    private void txtSLMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLMuonActionPerformed

    private void txtHanTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHanTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHanTraActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
         if(txtMaPhieuMuon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Phiếu mượn ");
            txtMaPhieuMuon.requestFocus();
            return;
        }
         boolean checkmapm = ChiTietPhieuMuonDAO.checkMaPM(txtMaPhieuMuon.getText());
        if(!checkmapm) {
            JOptionPane.showMessageDialog(this, "Đã tồn tại phiếu mượn: " + txtMaPhieuMuon.getText() +" ");
            return;
        }
        if(txtMaDocGia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Đọc giả ");
            txtMaDocGia.requestFocus();
            return;
        }
        boolean checkma = DocGiaDAO.checkMadg(txtMaDocGia.getText());
        if(checkma) {
            JOptionPane.showMessageDialog(this, "Chưa tồn tại đọc giả: " + txtMaDocGia.getText() +" ");
            return;
        }
        if(txtMaTL.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Tài liệu ");
            txtMaTL.requestFocus();
            return;
        }
         boolean checkmatl = TaiLieuDAO.checkMaTL(txtMaTL.getText());
        if(checkmatl) {
            JOptionPane.showMessageDialog(this, "Chưa tồn tại tài liệu: " + txtMaTL.getText() +" ");
            return;
        }
        if(txtSLMuon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Số lượng mượn ");
            txtSLMuon.requestFocus();
            return;
        }
        
            ChiTietPhieuMuon ctpm = new ChiTietPhieuMuon();
            ctpm.setMaPhieuMuon(txtMaPhieuMuon.getText());
            ctpm.setMaDocGia(txtMaDocGia.getText());
            ctpm.setTenDocGia(txtTenDG.getText());
            ctpm.setMaTaiLieu(txtMaTL.getText());
            ctpm.setTenTaiLieu(txtTenTL.getText());
            ctpm.setSoLuongMuon(Integer.valueOf(txtSLMuon.getText()));
            Date NgayMuon = Date.valueOf(txtNgayMuon.getText());
            ctpm.setNgayMuon(NgayMuon);
            Date HanTra = Date.valueOf(txtHanTra.getText());
            ctpm.setHanTra(HanTra);

            maNV = DangNhapDAO.LoadMaNhanVienHienTai();
            boolean kq = PhieuMuonDAO.themPhieuMuon(ctpm, maNV);
            if (kq == true) {
                 JOptionPane.showMessageDialog(this, "Thêm Phiếu mượn Thành công !!");
                setEnable_False();              
                hienThiDanhSach();
            }
            else{
                JOptionPane.showMessageDialog(this, "Thêm Phiếu mượn Thất Bại");
            }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtMaPhieuMuon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Phiếu mượn !!!");
            return;
        }
        boolean checkmapm = ChiTietPhieuMuonDAO.checkMaPM(txtMaPhieuMuon.getText());
        if(checkmapm) {
            JOptionPane.showMessageDialog(this, "Chưa tồn tại phiếu mượn: " + txtMaPhieuMuon.getText() +" !!!");
            return;
        }
        int delete = JOptionPane.showConfirmDialog(null, "Chắc chắn muốn Xóa Phiếu mượn có mã: "+txtMaPhieuMuon.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
        if (delete == 0) {
            boolean kq = PhieuMuonDAO.xoaPhieuMuon(txtMaPhieuMuon.getText());
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Xóa Phiếu mượn Thành công ");
                boolean updateslconlai = TaiLieuDAO.laySoLuongConLaiKhiXoa(txtSLMuon.getText(), txtMaTL.getText());
                if(updateslconlai == true){
                     JOptionPane.showMessageDialog(this, "Đã cập nhập lại số lượng tài liệu");
                }
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Xóa Phiếu mượn Thất Bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        if (txtMaPhieuMuon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Phiếu mượn !!!");
            return;
        }
        boolean checkmapm = ChiTietPhieuMuonDAO.checkMaPM(txtMaPhieuMuon.getText());
        if(checkmapm) {
            JOptionPane.showMessageDialog(this, "Chưa tồn tại phiếu mượn: " + txtMaPhieuMuon.getText() +" !!!");
            return;
        }
        if (check) {
            ChiTietPhieuMuon ctpm = new ChiTietPhieuMuon();
            ctpm.setMaPhieuMuon(txtMaPhieuMuon.getText());
            ctpm.setMaDocGia(txtMaDocGia.getText());
            ctpm.setTenDocGia(txtTenDG.getText());
            ctpm.setMaTaiLieu(txtMaTL.getText());
            ctpm.setTenTaiLieu(txtTenTL.getText());
            try {
                ctpm.setSoLuongMuon(Integer.valueOf(txtSLMuon.getText()));
            } catch (NumberFormatException e) {
                txtSLMuon.requestFocus();
                return;
            }
            Date NgayMuon = Date.valueOf(txtNgayMuon.getText());
            ctpm.setNgayMuon(NgayMuon);
            Date HanTra = Date.valueOf(txtHanTra.getText());
            ctpm.setHanTra(HanTra);
        
            maNV = DangNhapDAO.LoadMaNhanVienHienTai();
            boolean kq = PhieuMuonDAO.suaPhieuMuon(ctpm, maNV);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Cập nhật Phiếu mượn  thành công");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Cập nhật Phiếu mượn Thất Bại");
            btnSua.setText("Sửa");
            check = false;
        } else {
            int update = JOptionPane.showConfirmDialog(null, "Chỉnh sửa Phiếu mượn có mã: "+txtMaPhieuMuon.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
            if (update == 0) {
                check = true;
                setEnable_True();
                txtMaPhieuMuon.setEnabled(false);
                 btnThem.setEnabled(false);
                btnSua.setText("Lưu");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        setEnable_True();
        txtMaPhieuMuon.setText("PM");
        txtMaDocGia.setText("");
        txtTenDG.setText("");
        txtMaTL.setText("");
        txtTenTL.setText("");
        txtSLMuon.setText("");
        Date NgayMuon = Date.valueOf(java.time.LocalDate.now());
        txtNgayMuon.setText(String.valueOf(NgayMuon));
        hanTra.roll(Calendar.DATE, 7); 
        txtHanTra.setText(String.valueOf(dateFormat.format(hanTra.getTime())));
        txtMaDocGia.requestFocus();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnTKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKiemActionPerformed
        String str = txtTimKiem.getText();
        ArrayList<PhieuMuon> ds = PhieuMuonDAO.DanhSachPhieuMuonSearch(str);
        dtm.setRowCount(0);
        for(PhieuMuon pm: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(pm.getMaPhieuMuon());
             v.add(pm.getMaNVLap());
            v.add(pm.getMaDG());
            v.add(pm.getTinhTrang());
             v.add(pm.getNgayLap());
            dtm.addRow(v);
        }
        tblDSPhieuMuon.setModel(dtm);
    }//GEN-LAST:event_btnTKiemActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
  
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void tblDSPhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSPhieuMuonMouseClicked
        int row = this.tblDSPhieuMuon.getSelectedRow();
        String maPhieuMuon = (String) tblDSPhieuMuon.getValueAt(row, 0);
        ChiTietPhieuMuon chiTietPhieuMuon = ChiTietPhieuMuonDAO.LoadChiTietPhieuMuon(maPhieuMuon);
        txtMaPhieuMuon.setText(chiTietPhieuMuon.getMaPhieuMuon());
        txtMaDocGia.setText(chiTietPhieuMuon.getMaDocGia());
        txtTenDG.setText(chiTietPhieuMuon.getTenDocGia());
        txtMaTL.setText(chiTietPhieuMuon.getMaTaiLieu());
        txtTenTL.setText(chiTietPhieuMuon.getTenTaiLieu());
        txtSLMuon.setText(String.valueOf(chiTietPhieuMuon.getSoLuongMuon()));
        txtNgayMuon.setText(String.valueOf(chiTietPhieuMuon.getNgayMuon()));
        txtHanTra.setText(String.valueOf(chiTietPhieuMuon.getHanTra()));
    }//GEN-LAST:event_tblDSPhieuMuonMouseClicked

    private void txtMaDocGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaDocGiaFocusLost
        if(!txtMaDocGia.getText().isEmpty()) {
            String tenDG = DocGiaDAO.LoadTenDocGia(txtMaDocGia.getText());
            if (tenDG.equals("error")) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy Đọc giả "+txtMaDocGia.getText()+" ");
                txtMaDocGia.setText("");
                txtMaDocGia.requestFocus();
                return;
            } 
            else{
                txtTenDG.setText(tenDG);
            }
        }
    }//GEN-LAST:event_txtMaDocGiaFocusLost

    private void txtMaTLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaTLFocusLost
        if(!txtMaTL.getText().isEmpty()) {
            String tenTL = TaiLieuDAO.LoadTenTaiLieu(txtMaTL.getText());
            if (tenTL.equals("error")) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy Tài liệu "+ txtMaTL.getText()+"");
                txtMaTL.setText("");
                txtMaTL.requestFocus();
                return;
            } 
            else {
                txtTenTL.setText(tenTL);
            }
        }
    }//GEN-LAST:event_txtMaTLFocusLost

    private void txtSLMuonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSLMuonFocusLost
        int sl = -1, slConLai = -1, check = 1;
        slConLai = TaiLieuDAO.laySoLuongConLai(txtMaTL.getText());
        try {
            sl = Integer.valueOf(txtSLMuon.getText());
            check = 0;
        } catch (Exception e) {
            check = 1;
            JOptionPane.showMessageDialog(this, "Vui lòng nhập kiểu số");
        }
        if(check == 0) {
            if(sl > 5) {
                JOptionPane.showMessageDialog(this, "Số lượng mượn tối đa là 5");
            } else if(sl > slConLai) {
                JOptionPane.showMessageDialog(this, "Tài liệu chỉ còn: "+slConLai+" bản in !!!");
           }
        }
    }//GEN-LAST:event_txtSLMuonFocusLost

    private void setEnable_False() {
        txtMaPhieuMuon.setEnabled(false);
        txtMaDocGia.setEnabled(false);
        txtTenDG.setEnabled(false);
        txtMaTL.setEnabled(false);
        txtTenTL.setEnabled(false);
        txtSLMuon.setEnabled(false);
        txtNgayMuon.setEnabled(false);
        txtHanTra.setEnabled(false);        
        btnThem.setEnabled(false);
    }
    
    private void setEnable_True() {
        txtMaPhieuMuon.setEnabled(true);
        txtMaDocGia.setEnabled(true);
        txtMaTL.setEnabled(true);
        txtSLMuon.setEnabled(true);  
        btnThem.setEnabled(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTKiem;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nen;
    private javax.swing.JTable tblDSPhieuMuon;
    private javax.swing.JTextField txtHanTra;
    private javax.swing.JTextField txtMaDocGia;
    private javax.swing.JTextField txtMaPhieuMuon;
    private javax.swing.JTextField txtMaTL;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtSLMuon;
    private javax.swing.JTextField txtTenDG;
    private javax.swing.JTextField txtTenTL;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
