/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.TaiLieuDAO;
import POJO.TaiLieu;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class formTaiLieu extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    boolean check = false, checkBtnMoi = false;
    String ImagePath = null;
    /**
     * Creates new form QL_SachNew
     */
    public formTaiLieu() {
        initComponents();
        dtm.addColumn("Mã Tài liệu");
        dtm.addColumn("Tên Tài liệu");
        dtm.addColumn("Tác giả");
        dtm.addColumn("Tổng số");
        dtm.addColumn("Còn lại");
        dtm.addColumn("Giá");
        dtm.addColumn("Ảnh tài Liệu");
        setEnable_False();
        hienThiDanhSach();
        tblDSTaiLieu.setModel(dtm);
    }
    
    private void hienThiDanhSach() {
        ArrayList<TaiLieu> ds = TaiLieuDAO.DanhSachTaiLieu();
        dtm.setRowCount(0);
        for(TaiLieu tl: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(tl.getMaTaiLieu());
            v.add(tl.getTenTaiLieu());
            v.add(tl.getTacGia());
            v.add(tl.getSoLuong());
            v.add(tl.getConLai());
            v.add(tl.getGia());
            v.add(tl.getAnh());
            dtm.addRow(v);
        }
        tblDSTaiLieu.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSTaiLieu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaTaiLieu = new javax.swing.JTextField();
        txtTenTaiLieu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTacGia = new javax.swing.JTextField();
        txtTongSo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtConLai = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        label_imageTL = new javax.swing.JLabel();
        btnChon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(865, 555));
        setMinimumSize(new java.awt.Dimension(865, 555));
        setPreferredSize(new java.awt.Dimension(865, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThem.setBackground(new java.awt.Color(154, 221, 253));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, 30));

        btnXoa.setBackground(new java.awt.Color(154, 221, 253));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 100, -1));

        btnSua.setBackground(new java.awt.Color(154, 221, 253));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 100, 30));

        btnMoi.setBackground(new java.awt.Color(154, 221, 253));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 100, 30));

        btnPrint.setBackground(new java.awt.Color(255, 204, 51));
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(102, 0, 102));
        btnPrint.setText("Print");
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 130, 30));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 380, -1));

        btnTKiem.setBackground(new java.awt.Color(154, 221, 253));
        btnTKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTKiem.setText("Tìm kiếm");
        btnTKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 160, -1));

        tblDSTaiLieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblDSTaiLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Hiện trạng", "Loại sách"
            }
        ));
        tblDSTaiLieu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDSTaiLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSTaiLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSTaiLieu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 790, 190));

        jPanel2.setBackground(new java.awt.Color(154, 221, 253));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin tài liệu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Mã tài liệu:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Tên tài liệu:");

        txtMaTaiLieu.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtMaTaiLieu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaTaiLieu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaTaiLieuFocusLost(evt);
            }
        });
        txtMaTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTaiLieuActionPerformed(evt);
            }
        });

        txtTenTaiLieu.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTenTaiLieu.setToolTipText("");
        txtTenTaiLieu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTaiLieuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Số lượng:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Còn lại:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Tác giả:");

        txtTacGia.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTacGia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTacGiaActionPerformed(evt);
            }
        });

        txtTongSo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTongSo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTongSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongSoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Giá:");

        txtConLai.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtConLai.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtConLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConLaiActionPerformed(evt);
            }
        });

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtGia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        label_imageTL.setBackground(new java.awt.Color(51, 51, 255));
        label_imageTL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_imageTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hopstarter-Soft-Scraps-User-Administrator-Blue.16.png"))); // NOI18N
        label_imageTL.setText("Ảnh Tài liệu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)
                        .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTongSo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(label_imageTL, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtTongSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtConLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(label_imageTL, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 790, 190));

        btnChon.setBackground(new java.awt.Color(154, 221, 253));
        btnChon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChon.setText("Chọn ảnh");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });
        getContentPane().add(btnChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 120, -1));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 870, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTaiLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTaiLieuActionPerformed

    private void txtTenTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTaiLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTaiLieuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (txtTenTaiLieu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên Tài liệu ");
            txtTenTaiLieu.requestFocus();
            return;
        }
         boolean checkma = TaiLieuDAO.checkMaTL(txtMaTaiLieu.getText());
        if(!checkma) {
            JOptionPane.showMessageDialog(this, "Đã tồn tại tài liệu: " + txtMaTaiLieu.getText() +" !!!");
            return;
        }
        if (txtTacGia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tác giả ");
            txtTacGia.requestFocus();
            return;
        }
         if (txtTongSo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Số Lượng");
            txtTongSo.requestFocus();
            return;
        }
          if (txtConLai.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Số Lượng còn lại ");
            txtConLai.requestFocus();
            return;
        }
          if (txtGia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Giá ");
            txtGia.requestFocus();
            return;
        }
        TaiLieu tl = new TaiLieu();
        tl.setMaTaiLieu(txtMaTaiLieu.getText());
        tl.setSoLuong(Integer.valueOf(txtTongSo.getText()));
        tl.setTenTaiLieu(txtTenTaiLieu.getText());
        tl.setTacGia(txtTacGia.getText());
        tl.setGia(Integer.valueOf(txtGia.getText()));
        tl.setConLai(Integer.valueOf(txtConLai.getText()));
        tl.setAnh(ImagePath);
        if(checkBtnMoi) {
            boolean kq = TaiLieuDAO.themTaiLieu(tl);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Thêm Tài liệu Thành công !!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Thêm Tài liệu Thất Bại");
            btnChon.setEnabled(false);
            checkBtnMoi = false;
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKiemActionPerformed
        String str = txtTimKiem.getText();
        ArrayList<TaiLieu> ds = TaiLieuDAO.DanhSachTaiLieuSearch(str);
        dtm.setRowCount(0);
        for(TaiLieu tl: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(tl.getMaTaiLieu());
            v.add(tl.getTenTaiLieu());
            v.add(tl.getTacGia());
            v.add(tl.getSoLuong());
            v.add(tl.getConLai());
            v.add(tl.getGia());
            v.add(tl.getAnh());
            dtm.addRow(v);
        }
        tblDSTaiLieu.setModel(dtm);
    }//GEN-LAST:event_btnTKiemActionPerformed

    private void txtTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTacGiaActionPerformed

    private void txtTongSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongSoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongSoActionPerformed

    private void txtConLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConLaiActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtMaTaiLieu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Tài liệu !!!");
            return;
        }
         boolean checkma = TaiLieuDAO.checkMaTL(txtMaTaiLieu.getText());
        if(checkma) {
            JOptionPane.showMessageDialog(this, "Chưa tồn tại tài liệu: " + txtMaTaiLieu.getText() +" !!!");
            return;
        }
        int delete = JOptionPane.showConfirmDialog(null, "Chắc chắn muốn Xóa Tài liệu: "+txtMaTaiLieu.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
        if (delete == 0) {
            boolean kq = TaiLieuDAO.xoaTaiLieu(txtMaTaiLieu.getText());
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Xóa Tài liệu Thành công !!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Xóa Tài liệu Thất Bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtMaTaiLieu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Tài liệu !!!");
            check = false; 
            return;
        }
         boolean checkma = TaiLieuDAO.checkMaTL(txtMaTaiLieu.getText());
        if(checkma) {
            JOptionPane.showMessageDialog(this, "Chưa tồn tại tài liệu: " + txtMaTaiLieu.getText() +" !!!");
            return;
        }
        btnChon.setEnabled(true);
        if (check) {
            TaiLieu tl = new TaiLieu();
            tl.setMaTaiLieu(txtMaTaiLieu.getText());
            tl.setTenTaiLieu(txtTenTaiLieu.getText());
            tl.setTacGia(txtTacGia.getText());
            tl.setSoLuong(Integer.valueOf(txtTongSo.getText()));
            tl.setConLai(Integer.valueOf(txtConLai.getText()));
            tl.setGia(Integer.valueOf(txtGia.getText()));
            tl.setAnh(ImagePath);
            boolean kq = TaiLieuDAO.suaTaiLieu(tl);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Cập nhật Tài liệu thành công!!!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Cập nhật Tài liệu Thất Bại !");
            btnSua.setText("Sửa");
            check = false;
        } else {
            int update = JOptionPane.showConfirmDialog(null, "Chỉnh sửa Tài liệu có mã: "+txtMaTaiLieu.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
            if (update == 0) {
                check = true;
                setEnable_True();
                txtMaTaiLieu.setEnabled(false);
                 if(checkma) {
                    JOptionPane.showMessageDialog(this, "Chưa tồn tại tài liệu: " + txtMaTaiLieu.getText() +" !!!");
                    return;
                }
                btnSua.setText("Lưu");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        btnThem.setEnabled(true);
        btnChon.setEnabled(true);
        txtMaTaiLieu.setText("TL");
        txtTenTaiLieu.setText("");
        txtTacGia.setText("");
        txtTongSo.setText("");
        txtConLai.setText("");
        txtGia.setText("");
        txtTenTaiLieu.requestFocus();
        setEnable_True();
        checkBtnMoi = true;
    }//GEN-LAST:event_btnMoiActionPerformed

    private void tblDSTaiLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSTaiLieuMouseClicked
        int row = this.tblDSTaiLieu.getSelectedRow();
        txtMaTaiLieu.setText((String) tblDSTaiLieu.getValueAt(row, 0));
        txtTenTaiLieu.setText((String) tblDSTaiLieu.getValueAt(row, 1));
        txtTacGia.setText((String) tblDSTaiLieu.getValueAt(row, 2));
        txtTongSo.setText((String) String.valueOf(tblDSTaiLieu.getValueAt(row, 3)));
        txtConLai.setText((String) String.valueOf(tblDSTaiLieu.getValueAt(row, 4)));
        txtGia.setText((String) String.valueOf(tblDSTaiLieu.getValueAt(row, 5)));
        ImagePath = (String) tblDSTaiLieu.getValueAt(row, 6);
        label_imageTL.setIcon(resizeImage(ImagePath));
    }//GEN-LAST:event_tblDSTaiLieuMouseClicked

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
      
          try {
            JFileChooser chooser = new JFileChooser("..\\QLTV\\src\\img");
            chooser.setDialogTitle("Mở File");
            chooser.showOpenDialog(null);
            File file = chooser.getSelectedFile();
            ImagePath = file.getAbsolutePath().replace("//","--");
        if(ImagePath != null)
            label_imageTL.setIcon(frameIcon);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn Ảnh");
        }
    }//GEN-LAST:event_btnChonActionPerformed

    private void txtMaTaiLieuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaTaiLieuFocusLost
        TaiLieu tl = TaiLieuDAO.LoadChiTietTaiLieu(txtMaTaiLieu.getText());
        txtTenTaiLieu.setText(tl.getTenTaiLieu());
        txtGia.setText(String.valueOf(tl.getGia()));
        txtTacGia.setText(tl.getTacGia());
    }//GEN-LAST:event_txtMaTaiLieuFocusLost


    private void setEnable_False() {
        txtMaTaiLieu.setEnabled(false);
        txtTenTaiLieu.setEnabled(false);
        txtTacGia.setEnabled(false);
        txtTongSo.setEnabled(false);
        txtConLai.setEnabled(false);
        txtGia.setEnabled(false);
        btnThem.setEnabled(false);
    }
    
    private void setEnable_True() {
          txtMaTaiLieu.setEnabled(true);
        txtTenTaiLieu.setEnabled(true);
        txtTacGia.setEnabled(true);
        txtTongSo.setEnabled(true);
        txtConLai.setEnabled(true);
        txtGia.setEnabled(true);
    }

    
    public ImageIcon resizeImage(String ImagePath) {   
        ImageIcon icon = new ImageIcon(ImagePath);
        Image img = icon.getImage();
        Image newImg = img.getScaledInstance(102, 118, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTKiem;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_imageTL;
    private javax.swing.JTable tblDSTaiLieu;
    private javax.swing.JTextField txtConLai;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaTaiLieu;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenTaiLieu;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongSo;
    // End of variables declaration//GEN-END:variables
}
