/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DangNhapDAO;
import DAO.PhieuPhatDAO;
import DAO.PhieuTraDAO;
import DAO.TaiLieuDAO;
import DAO.ChiTietPhieuTraDAO;
import DAO.ChiTietPhieuPhatDAO;
import DAO.LyDoPhatDAO;
import POJO.ChiTietPhieuPhat;
import POJO.ChiTietPhieuTra;
import POJO.LyDoPhat;
import POJO.PhieuPhat;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Hashtable;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class formPhieuPhat extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Calendar hanTra = Calendar.getInstance();
    boolean check = false, flag = false;
    String maNV;
    /**
     * Creates new form QL_MuonTaiLieu
     */
    public formPhieuPhat() {
        initComponents();
        maNV = DangNhapDAO.LoadMaNhanVienHienTai();
        dtm.addColumn("Mã Phiếu phạt");
        dtm.addColumn("Mã Phiếu trả");
        dtm.addColumn("Mã Đọc giả");
        dtm.addColumn("Mã Nhân viên");
        dtm.addColumn("Ngày lập");
        tblDSPhieuPhat.setModel(dtm);
        LoadComboboxLyDo();
        LoadCombobox();
        setEnable_False();
        hienThiDanhSach();
    }
    private void LoadCombobox(){
        List<String> ds_MaPhieuTra = PhieuPhatDAO.layDSMaPhieuTra();
        for (String maPhieuTra : ds_MaPhieuTra) {
            cboMaPhieuTra.addItem(maPhieuTra);
        }
        cboMaPhieuTra.setSelectedIndex(-1);
    }
     private void LoadComboboxLyDo(){
        List<String> ds_LydoPhat = LyDoPhatDAO.LoadDanhSachMaPhieuMuon();
        for (String malydo : ds_LydoPhat) {
            cboLyDo.addItem(malydo);
        }
        cboLyDo.setSelectedIndex(-1);
    }
    private void hienThiDanhSach() {
        ArrayList<PhieuPhat> ds = PhieuPhatDAO.DanhSachPhieuPhat();
        dtm.setRowCount(0);
        for(PhieuPhat pp: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(pp.getMaPhieuPhat());
            v.add(pp.getMaPhieuTra());
            v.add(pp.getMaDocGia());
            v.add(pp.getMaNV());
            v.add(pp.getNgayLap());
            dtm.addRow(v);
        }
        tblDSPhieuPhat.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaPhieuPhat = new javax.swing.JTextField();
        txtMaDocGia = new javax.swing.JTextField();
        txtTenDG = new javax.swing.JTextField();
        txtNgayLap = new javax.swing.JTextField();
        txtMaTL = new javax.swing.JTextField();
        txtTenTL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboMaPhieuTra = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTongTienPhat = new javax.swing.JTextField();
        cboLyDo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtTenLyDo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTienLyDoPhat = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnTKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSPhieuPhat = new javax.swing.JTable();
        nen = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(865, 555));
        setMinimumSize(new java.awt.Dimension(865, 555));
        setPreferredSize(new java.awt.Dimension(865, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(154, 221, 253));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết Phiếu Phạt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Mã phiếu phạt:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Mã đọc giả:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Tên đọc giả:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Ngày lập:");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Mã Lý do:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mã tài liệu:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tên tài liệu:");

        txtMaPhieuPhat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaPhieuPhat.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaPhieuPhat.setEnabled(false);
        txtMaPhieuPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhieuPhatActionPerformed(evt);
            }
        });

        txtMaDocGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaDocGia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaDocGia.setEnabled(false);
        txtMaDocGia.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtMaDocGiaInputMethodTextChanged(evt);
            }
        });
        txtMaDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDocGiaActionPerformed(evt);
            }
        });

        txtTenDG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenDG.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenDG.setEnabled(false);
        txtTenDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDGActionPerformed(evt);
            }
        });

        txtNgayLap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNgayLap.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayLapActionPerformed(evt);
            }
        });

        txtMaTL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaTL.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaTL.setEnabled(false);
        txtMaTL.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtMaTLInputMethodTextChanged(evt);
            }
        });
        txtMaTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTLActionPerformed(evt);
            }
        });

        txtTenTL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenTL.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenTL.setEnabled(false);
        txtTenTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTLActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Mã phiếu trả:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cboMaPhieuTra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboMaPhieuTra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaPhieuTraItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Số lượng:");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoLuong.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSoLuong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoLuongFocusLost(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Tổng tiền phạt:");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtTongTienPhat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTongTienPhat.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTongTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienPhatActionPerformed(evt);
            }
        });

        cboLyDo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboLyDo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLyDoItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Tên Lý Do:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtTenLyDo.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Số tiền phạt:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtTienLyDoPhat.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoLuong)
                    .addComponent(txtMaPhieuPhat)
                    .addComponent(cboMaPhieuTra, 0, 170, Short.MAX_VALUE)
                    .addComponent(cboLyDo, 0, 170, Short.MAX_VALUE)
                    .addComponent(txtTenLyDo)
                    .addComponent(txtTienLyDoPhat))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTongTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenTL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaPhieuPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMaPhieuTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cboLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtTenLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtTienLyDoPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTongTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 760, 230));

        btnThem.setBackground(new java.awt.Color(154, 221, 253));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 90, -1));

        btnXoa.setBackground(new java.awt.Color(154, 221, 253));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 90, -1));

        btnSua.setBackground(new java.awt.Color(154, 221, 253));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 90, -1));

        btnMoi.setBackground(new java.awt.Color(154, 221, 253));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 90, -1));

        btnTKiem.setBackground(new java.awt.Color(154, 221, 253));
        btnTKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTKiem.setText("Tìm kiếm");
        btnTKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 170, -1));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 430, -1));

        tblDSPhieuPhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblDSPhieuPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title1", "Title2", "Title3", "Title4"
            }
        ));
        tblDSPhieuPhat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDSPhieuPhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSPhieuPhatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSPhieuPhat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 760, 190));

        nen.setBackground(java.awt.Color.pink);
        nen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen3.png"))); // NOI18N
        nen.setMaximumSize(new java.awt.Dimension(735, 555));
        nen.setMinimumSize(new java.awt.Dimension(735, 555));
        getContentPane().add(nen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 880, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaPhieuPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhieuPhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhieuPhatActionPerformed

    private void txtMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDocGiaActionPerformed

    }//GEN-LAST:event_txtMaDocGiaActionPerformed

    private void txtTenDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDGActionPerformed

    private void txtNgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayLapActionPerformed

    private void txtMaTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTLActionPerformed

    private void txtTenTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTLActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String strMaPhieuTra = String.valueOf(cboMaPhieuTra.getSelectedItem());
        String strLyDo = String.valueOf(cboLyDo.getSelectedItem());
        if(strMaPhieuTra.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Mã Phiếu Trả ");
            cboMaPhieuTra.requestFocus();
            return;
        }
        if(strLyDo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Lý do ");
            cboLyDo.requestFocus();
            return;
        }
        
        if(txtSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Số lượng ");
            txtSoLuong.requestFocus();
            return;
        }
        if(txtMaPhieuPhat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phiếu phạt");
            txtMaPhieuPhat.requestFocus();
            return;
        } 
         boolean checkmapm = ChiTietPhieuPhatDAO.checkMaPP(txtMaPhieuPhat.getText());
        if(!checkmapm) {
            JOptionPane.showMessageDialog(this, "Đã tồn tại phiếu phát: " + txtMaPhieuPhat.getText() +" ");
            return;
        }
            
        ChiTietPhieuPhat ctpp = new ChiTietPhieuPhat();
        ctpp.setMaPhieuPhat(txtMaPhieuPhat.getText());
        ctpp.setMaPhieuTra(String.valueOf(cboMaPhieuTra.getSelectedItem()));
        ctpp.setMaLyDo(String.valueOf(cboLyDo.getSelectedItem()));
        ctpp.setLyDo(txtTenLyDo.getText());
        ctpp.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
        ctpp.setSoTienPhat(Integer.valueOf(txtTienLyDoPhat.getText()));
        ctpp.setTongTienPhat(Integer.valueOf(txtTongTienPhat.getText()));
        ctpp.setMaDocGia(txtMaDocGia.getText());
        ctpp.setTenDocGia(txtTenDG.getText());
        ctpp.setMaTaiLieu(txtMaTL.getText());
        ctpp.setTenTaiLieu(txtTenTL.getText());
        Date NgayLap = Date.valueOf(txtNgayLap.getText());
        ctpp.setNgayLap(NgayLap);
        
        boolean kq = PhieuPhatDAO.themPhieuPhat(ctpp, maNV);
        if (kq == true) {
            setEnable_False();
            hienThiDanhSach();
        }
        else JOptionPane.showMessageDialog(this, "Thêm Phiếu phạt Thất Bại");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        
        if (txtMaPhieuPhat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Phiếu phạt !!!");
            return;
        }
          boolean checkmapp = ChiTietPhieuPhatDAO.checkMaPP(txtMaPhieuPhat.getText());
        if(checkmapp) {
            JOptionPane.showMessageDialog(this, "Chưa tồn tại phiếu phát: " + txtMaPhieuPhat.getText() +" ");
            return;
        }
        int delete = JOptionPane.showConfirmDialog(null, "Chắc chắn muốn Xóa Phiếu phạt có mã: "+txtMaPhieuPhat.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
        if (delete == 0) {
            boolean kq = PhieuPhatDAO.xoaPhieuPhat(txtMaPhieuPhat.getText());
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Xóa Phiếu phạt Thành công !!");
                setEnable_False();
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Xóa Phiếu phạt Thất Bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtMaPhieuPhat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Phiếu trả !!!");
            return;
        }
          boolean checkmapp = ChiTietPhieuPhatDAO.checkMaPP(txtMaPhieuPhat.getText());
        if(checkmapp) {
            JOptionPane.showMessageDialog(this, "Chưa tồn tại phiếu phát: " + txtMaPhieuPhat.getText() +" ");
            return;
        }
        if (check) {
            ChiTietPhieuPhat ctpp = new ChiTietPhieuPhat();
            ctpp.setMaPhieuPhat(txtMaPhieuPhat.getText());
            ctpp.setMaPhieuTra(String.valueOf(cboMaPhieuTra.getSelectedItem()));
            ctpp.setMaLyDo(String.valueOf(cboLyDo.getSelectedItem()));
            ctpp.setLyDo(String.valueOf(cboLyDo.getSelectedItem()));
            ctpp.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
            ctpp.setSoTienPhat(Integer.valueOf(txtTienLyDoPhat.getText()));
             ctpp.setTongTienPhat(Integer.valueOf(txtTongTienPhat.getText()));
            ctpp.setMaDocGia(txtMaDocGia.getText());
            ctpp.setTenDocGia(txtTenDG.getText());
            ctpp.setMaTaiLieu(txtMaTL.getText());
            ctpp.setTenTaiLieu(txtTenTL.getText());
            Date NgayLap = Date.valueOf(txtNgayLap.getText());
            ctpp.setNgayLap(NgayLap);
            
            boolean kq = PhieuPhatDAO.suaPhieuPhat(ctpp, maNV);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Cập nhật Phiếu phạt thành công");
                setEnable_False();
                
                hienThiDanhSach();
            }
            else JOptionPane.showMessageDialog(this, "Cập nhật Phiếu phạt Thất Bại");
            btnSua.setText("Sửa");
            check = false;
        } else if(!flag) {
            int update = JOptionPane.showConfirmDialog(null, "Chỉnh sửa Phiếu phạt có mã: "+txtMaPhieuPhat.getText()+" ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
            if (update == 0) {
                check = true;
                setEnable_True();
                btnThem.setEnabled(false);
                btnSua.setText("Lưu");
            }
        }
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        setEnable_True();
        txtMaPhieuPhat.setText("PP");
        cboMaPhieuTra.setSelectedIndex(-1);
        txtMaDocGia.setText("");
        txtTenDG.setText("");
        txtMaTL.setText("");
        txtTenTL.setText("");
        cboLyDo.setSelectedIndex(-1);
         txtTenLyDo.setText("");
         txtTienLyDoPhat.setText("");
        txtSoLuong.setText("");
        txtTongTienPhat.setText("");
        Date NgayLap = Date.valueOf(java.time.LocalDate.now());
        txtNgayLap.setText(String.valueOf(NgayLap));
        txtMaDocGia.requestFocus();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnTKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKiemActionPerformed
        String str = txtTimKiem.getText();
        
        ArrayList<PhieuPhat> ds = PhieuPhatDAO.DanhSachPhieuPhatSearch(str);
        dtm.setRowCount(0);
        for(PhieuPhat pp: ds) {
            Vector<Object> v = new Vector<Object>();
            v.add(pp.getMaPhieuPhat());
            v.add(pp.getMaPhieuTra());
            v.add(pp.getMaDocGia());
            v.add(pp.getMaNV());
            v.add(pp.getNgayLap());
            dtm.addRow(v);
        }
        tblDSPhieuPhat.setModel(dtm);
    }//GEN-LAST:event_btnTKiemActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
  
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void tblDSPhieuPhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSPhieuPhatMouseClicked
        
        int row = this.tblDSPhieuPhat.getSelectedRow();
        String maPhieuPhat = (String) tblDSPhieuPhat.getValueAt(row, 0);
        ChiTietPhieuPhat chiTietPhieuPhat = ChiTietPhieuPhatDAO.LoadChiTietPhieuPhat(maPhieuPhat);
        txtMaPhieuPhat.setText(chiTietPhieuPhat.getMaPhieuPhat());
        cboMaPhieuTra.setSelectedItem(String.valueOf(chiTietPhieuPhat.getMaPhieuTra()));
        txtMaDocGia.setText(chiTietPhieuPhat.getMaDocGia());
        txtTenDG.setText(chiTietPhieuPhat.getTenDocGia());
        txtMaTL.setText(chiTietPhieuPhat.getMaTaiLieu());
        txtTenTL.setText(chiTietPhieuPhat.getTenTaiLieu());
        cboLyDo.setSelectedItem(String.valueOf(chiTietPhieuPhat.getMaLyDo()));
        txtTenLyDo.setText(chiTietPhieuPhat.getLyDo());
        txtSoLuong.setText(String.valueOf(chiTietPhieuPhat.getSoLuong()));
        txtTienLyDoPhat.setText(String.valueOf(chiTietPhieuPhat.getSoTienPhat()));
        txtTongTienPhat.setText(String.valueOf(chiTietPhieuPhat.getTongTienPhat()));
        txtNgayLap.setText(String.valueOf(chiTietPhieuPhat.getNgayLap()));
    }//GEN-LAST:event_tblDSPhieuPhatMouseClicked

    private void txtMaDocGiaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtMaDocGiaInputMethodTextChanged
    }//GEN-LAST:event_txtMaDocGiaInputMethodTextChanged

    private void txtMaTLInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtMaTLInputMethodTextChanged
    }//GEN-LAST:event_txtMaTLInputMethodTextChanged

    private void cboMaPhieuTraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaPhieuTraItemStateChanged
        ChiTietPhieuTra chiTietPhieuTra = ChiTietPhieuTraDAO.LoadChiTietPhieuTra(String.valueOf(evt.getItem()));
        txtMaDocGia.setText(chiTietPhieuTra.getMaDocGia());
        txtTenDG.setText(chiTietPhieuTra.getTenDocGia());
        txtMaTL.setText(chiTietPhieuTra.getMaTaiLieu());
        txtTenTL.setText(chiTietPhieuTra.getTenTaiLieu());
    }//GEN-LAST:event_cboMaPhieuTraItemStateChanged

    private void txtSoLuongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoLuongFocusLost
        // TODO add your handling code here:
         int slphat = -1, check = 1,tong = -1;
        try {
            slphat = Integer.valueOf(txtSoLuong.getText());
            check = 0;
        } catch (Exception e) {
            check = 1;
            JOptionPane.showMessageDialog(this, "Vui lòng nhập kiểu số!");
        }
        if(check == 0) {
             int slTra = ChiTietPhieuTraDAO.LoadSoLuongTra(String.valueOf(cboMaPhieuTra.getSelectedItem()));
            if(slphat > slTra) {
                txtSoLuong.setText("");
                txtSoLuong.requestFocus();
                JOptionPane.showMessageDialog(this, "Số Tài liệu đã trả là: " + slTra);
            } else{
                tong = Integer.valueOf(txtTienLyDoPhat.getText()) *  Integer.valueOf(txtSoLuong.getText());
                txtTongTienPhat.setText(String.valueOf(tong));
            }
        }       
    }//GEN-LAST:event_txtSoLuongFocusLost

    private void txtTongTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienPhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienPhatActionPerformed

    private void cboLyDoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLyDoItemStateChanged
        // TODO add your handling code here:
        LyDoPhat lydo = LyDoPhatDAO.LoadChiTietLyDo(String.valueOf(evt.getItem()));
        txtTenLyDo.setText(lydo.getLyDo());
        txtTienLyDoPhat.setText(String.valueOf(lydo.getSoTienPhat()) );
    }//GEN-LAST:event_cboLyDoItemStateChanged

    

    
    
    private void setEnable_False() {
        txtMaPhieuPhat.setEnabled(false);
        txtMaDocGia.setEnabled(false);
        txtTenDG.setEnabled(false);
        txtMaTL.setEnabled(false);
        txtTenTL.setEnabled(false);
        cboLyDo.setEnabled(false);
        txtNgayLap.setEnabled(false);
        cboMaPhieuTra.setEnabled(false);    
        txtTenLyDo.setEnabled(false);
        txtTienLyDoPhat.setEnabled(false);
        txtTongTienPhat.setEnabled(false);
        btnThem.setEnabled(false);
    }
    
    private void setEnable_True() {
         txtMaPhieuPhat.setEnabled(true);
        cboMaPhieuTra.setEnabled(true);  
        cboLyDo.setEnabled(true);       
        btnThem.setEnabled(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTKiem;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLyDo;
    private javax.swing.JComboBox<String> cboMaPhieuTra;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nen;
    private javax.swing.JTable tblDSPhieuPhat;
    private javax.swing.JTextField txtMaDocGia;
    private javax.swing.JTextField txtMaPhieuPhat;
    private javax.swing.JTextField txtMaTL;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenDG;
    private javax.swing.JTextField txtTenLyDo;
    private javax.swing.JTextField txtTenTL;
    private javax.swing.JTextField txtTienLyDoPhat;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongTienPhat;
    // End of variables declaration//GEN-END:variables
}
