/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class formTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public formTrangChu(String user) {
        this.setTitle("Quản lý Thư viện");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        initComponents();
        txtUser.setText(user);
    }
    
    public formTrangChu() {
        this.setTitle("Quản lý Thư viện");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        initComponents();
    }
    public void EnablebtnQLNV() {
        btnQLNV.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQLNV = new javax.swing.JButton();
        btnQLTL = new javax.swing.JButton();
        btnQLDG = new javax.swing.JButton();
        btnPP = new javax.swing.JButton();
        btnQLMuon = new javax.swing.JButton();
        btnQLTra = new javax.swing.JButton();
        pnl_View = new javax.swing.JDesktopPane();
        icon = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        hinhnen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLNV.setBackground(new java.awt.Color(255, 153, 153));
        btnQLNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen3.png"))); // NOI18N
        btnQLNV.setText("Quản lý Nhân viên");
        btnQLNV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        btnQLNV.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnQLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNV.setPreferredSize(new java.awt.Dimension(1800, 1086));
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 200, 60));

        btnQLTL.setBackground(new java.awt.Color(255, 153, 153));
        btnQLTL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnQLTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen3.png"))); // NOI18N
        btnQLTL.setText("Quản lý Tài liệu");
        btnQLTL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        btnQLTL.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnQLTL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTLActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 200, 60));

        btnQLDG.setBackground(new java.awt.Color(255, 153, 153));
        btnQLDG.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnQLDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen3.png"))); // NOI18N
        btnQLDG.setText("Quản lý Đọc giả");
        btnQLDG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        btnQLDG.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnQLDG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDGActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 200, 60));

        btnPP.setBackground(new java.awt.Color(255, 153, 153));
        btnPP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen3.png"))); // NOI18N
        btnPP.setText("Quản lý Phiếu Phạt");
        btnPP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        btnPP.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnPP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPPActionPerformed(evt);
            }
        });
        getContentPane().add(btnPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 200, 60));

        btnQLMuon.setBackground(new java.awt.Color(255, 153, 153));
        btnQLMuon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnQLMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen3.png"))); // NOI18N
        btnQLMuon.setText("Quản lý Phiếu Mượn");
        btnQLMuon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        btnQLMuon.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnQLMuon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLMuonActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 200, 60));

        btnQLTra.setBackground(new java.awt.Color(255, 153, 153));
        btnQLTra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnQLTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen3.png"))); // NOI18N
        btnQLTra.setText("Quản lý Phiếu Trả");
        btnQLTra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        btnQLTra.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnQLTra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTraActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 200, 60));

        pnl_View.setBackground(new java.awt.Color(154, 221, 253));
        pnl_View.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnl_View.setMaximumSize(new java.awt.Dimension(899, 555));
        pnl_View.setMinimumSize(new java.awt.Dimension(899, 555));
        getContentPane().add(pnl_View, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 865, 555));

        icon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hopstarter-Soft-Scraps-User-Administrator-Blue.16.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 30));

        txtUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 255, 255));
        txtUser.setText("User");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 160, 30));

        btnThoat.setBackground(new java.awt.Color(255, 153, 153));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen3.png"))); // NOI18N
        btnThoat.setText("Log Out");
        btnThoat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        btnThoat.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 60));

        hinhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhnen4.png"))); // NOI18N
        hinhnen.setMaximumSize(new java.awt.Dimension(990, 600));
        hinhnen.setMinimumSize(new java.awt.Dimension(990, 600));
        hinhnen.setPreferredSize(new java.awt.Dimension(990, 600));
        getContentPane().add(hinhnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDGActionPerformed

        formDocGia DocGia = new formDocGia();

        
        setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ifu= DocGia.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null); 

        DocGia.setVisible(true);
        this.pnl_View.removeAll();
        this.pnl_View.add(DocGia);
    }//GEN-LAST:event_btnQLDGActionPerformed

    private void btnPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPPActionPerformed

        formPhieuPhat PhieuPhat = new formPhieuPhat();

        setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ifu= PhieuPhat.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null); 

        PhieuPhat.setVisible(true);
        this.pnl_View.removeAll();
        this.pnl_View.add(PhieuPhat);
    }//GEN-LAST:event_btnPPActionPerformed

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed

        formNhanVien NhanVien = new formNhanVien();

        setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ifu= NhanVien.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null); 

        NhanVien.setVisible(true);
        this.pnl_View.removeAll();
        this.pnl_View.add(NhanVien);
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void btnQLTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTLActionPerformed

        formTaiLieu TaiLieu = new formTaiLieu();

        setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ifu= TaiLieu.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null); 

        TaiLieu.setVisible(true);
        this.pnl_View.removeAll();
        this.pnl_View.add(TaiLieu);
    }//GEN-LAST:event_btnQLTLActionPerformed

    private void btnQLTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTraActionPerformed
        formPhieuTra Tra = new formPhieuTra();

        setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ifu= Tra.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null); 

        Tra.setVisible(true);
        this.pnl_View.removeAll();
        this.pnl_View.add(Tra);
    }//GEN-LAST:event_btnQLTraActionPerformed

    private void btnQLMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLMuonActionPerformed
        formPhieuMuon Muon = new formPhieuMuon();

        setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ifu= Muon.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null); 

        Muon.setVisible(true);
        this.pnl_View.removeAll();
        this.pnl_View.add(Muon);
    }//GEN-LAST:event_btnQLMuonActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
         int logout = JOptionPane.showConfirmDialog(null, "Bạn muốn đăng xuất ?", "Thông báo",JOptionPane.YES_NO_CANCEL_OPTION);
        if (logout == 0) {
            this.setVisible(false);
            formDangNhap dangNhap = new formDangNhap();
            dangNhap.setLocationRelativeTo(null);
            dangNhap.setVisible(true);
        }
    }//GEN-LAST:event_btnThoatActionPerformed


    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPP;
    private javax.swing.JButton btnQLDG;
    private javax.swing.JButton btnQLMuon;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQLTL;
    private javax.swing.JButton btnQLTra;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel hinhnen;
    private javax.swing.JLabel icon;
    private javax.swing.JDesktopPane pnl_View;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
